# Generated by Django 5.2 on 2025-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_comptable',
            field=models.BooleanField(default=False),
        ),
    ]
