# Generated by Django 5.2 on 2025-05-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_connection',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
