# Generated by Django 5.2 on 2025-04-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='offres/destination')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='offres/')),
                ('active', models.BooleanField(default=True)),
                ('mise_en_avant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='travel.categorie')),
                ('destinations', models.ManyToManyField(related_name='offres', to='travel.destination')),
            ],
        ),
        migrations.CreateModel(
            name='DepartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_total', models.PositiveIntegerField()),
                ('places_dispo', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('complet', 'Complet')], default='ouvert', max_length=10)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_details', to='travel.offre')),
            ],
        ),
        migrations.CreateModel(
            name='OffreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='offres/gallery/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.offre')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('obligatoire', models.BooleanField(default=False)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='travel.offre')),
            ],
        ),
    ]
