# Generated by Django 5.2 on 2025-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='populaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offre',
            name='populaire',
            field=models.BooleanField(default=False),
        ),
    ]
