# Generated by Django 5.2 on 2025-04-23 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_destination_populaire_offre_populaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('effectue', 'Effectué'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('methode', models.CharField(choices=[('carte_bancaire', 'Carte Bancaire'), ('sur_place', 'Paiement sur place'), ('virement_bancaire', 'Virement bancaire'), ('cheque', 'Chèque')], max_length=30)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='travel.booking')),
            ],
        ),
    ]
