# Generated by Django 5.2 on 2025-04-23 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_booking_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffrePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveIntegerField(help_text="Jour de l'activité (ex: 1 pour le premier jour)")),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='offres/plannings/')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='travel.offre')),
            ],
            options={
                'ordering': ['jour'],
            },
        ),
    ]
