# Generated by Django 5.2 on 2025-04-24 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_offreplanning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=100, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payée', 'Payée'), ('annulée', 'Annulée')], default='en_attente', max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='travel.booking')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('carte_bancaire', 'Carte Bancaire'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('espèces', 'Espèces')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('comptable', models.ForeignKey(blank=True, limit_choices_to={'profile__is_comptable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='travel.facture')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_partenaire', models.CharField(choices=[('hotel', 'Hôtel'), ('transport', 'Transport'), ('guide', 'Guide touristique'), ('agence_locale', 'Agence locale'), ('autre', 'Autre')], max_length=50)),
                ('contact_nom', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('commercial_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_gérés', to=settings.AUTH_USER_MODEL)),
                ('offres_associees', models.ManyToManyField(blank=True, related_name='partenaires', to='travel.offre')),
            ],
        ),
        migrations.CreateModel(
            name='ContratPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats_partenaire/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié')], default='actif', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='travel.partenaire')),
            ],
        ),
    ]
