# Generated by Django 5.2 on 2025-04-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_facture_historiquepaiement_partenaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='offres_associees',
            field=models.ManyToManyField(blank=True, null=True, related_name='partenaires', to='travel.offre'),
        ),
    ]
