# Generated by Django 5.2 on 2025-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_partenaire_offres_associees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='offres_associees',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='offres_associees',
            field=models.TextField(blank=True, null=True),
        ),
    ]
