# Generated by Django 5.2 on 2025-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_partenaire_offres_associees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='options_extras',
            field=models.ManyToManyField(blank=True, to='travel.optionextra'),
        ),
    ]
