# Generated by Django 5.2 on 2025-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_facture_options_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='avance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
