# Generated by Django 5.2 on 2025-04-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_payment_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='prix_offre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
