# Generated by Django 5.2 on 2025-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_facture_prix_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepaiement',
            name='fichier_facture',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
    ]
