# Generated by Django 5.2 on 2025-05-06 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_latitude_hotel_longitude_hotel_prix_init'),
        ('travel', '0011_historiquepaiement_fichier_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiementHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('carte_bancaire', 'Carte Bancaire'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('espèces', 'Espèces')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('fichier_facture', models.FileField(blank=True, null=True, upload_to='factures_hotel/')),
                ('comptable', models.ForeignKey(blank=True, limit_choices_to={'profile__is_comptable': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_hotel', to='hotel.facture')),
            ],
        ),
    ]
