# Generated by Django 5.2 on 2025-05-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise'), ('groupe', 'Groupe'), ('scolaire', 'Scolaire')], default='particulier', max_length=50),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='hotels/gallery/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.hotel')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
